<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipes')->insert([
            [
                'id_product' => 1,
                'id_ingredient' => 13,
                'amount' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 1,
                'id_ingredient' => 5,
                'amount' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'id_ingredient' => 13,
                'amount' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'id_ingredient' => 5,
                'amount' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 2,
                'id_ingredient' => 19,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'id_ingredient' => 13,
                'amount' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 3,
                'id_ingredient' => 5,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'id_ingredient' => 13,
                'amount' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'id_ingredient' => 5,
                'amount' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 4,
                'id_ingredient' => 7,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'id_ingredient' => 13,
                'amount' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'id_ingredient' => 5,
                'amount' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 5,
                'id_ingredient' => 18,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'id_ingredient' => 14,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 6,
                'id_ingredient' => 5,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'id_ingredient' => 14,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'id_ingredient' => 5,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 7,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'id_ingredient' => 7,
                'amount' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'id_ingredient' => 5,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 8,
                'id_ingredient' => 2,
                'amount' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 9,
                'id_ingredient' => 14,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 10,
                'id_ingredient' => 14,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 12,
                'id_ingredient' => 14,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 13,
                'id_ingredient' => 14,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'id_ingredient' => 1,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'id_ingredient' => 3,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 14,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'id_ingredient' => 1,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'id_ingredient' => 3,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'id_ingredient' => 2,
                'amount' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 15,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'id_ingredient' => 1,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'id_ingredient' => 2,
                'amount' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'id_ingredient' => 3, 
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 16,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'id_ingredient' => 1,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'id_ingredient' => 3,
                'amount' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 17,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'id_ingredient' => 1,
                'amount' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'id_ingredient' => 2,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'id_ingredient' => 3,
                'amount' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 18,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'id_ingredient' => 6,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 19,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'id_ingredient' => 1,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'id_ingredient' => 6,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 20,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'id_ingredient' => 6,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 21,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'id_ingredient' => 1,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'id_ingredient' => 6,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'id_ingredient' => 2,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 22,
                'id_ingredient' => 4,
                'amount' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'id_ingredient' => 19,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'id_ingredient' => 2,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'id_ingredient' => 4,
                'amount' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 23,
                'id_ingredient' => 17,
                'amount' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'id_ingredient' => 1,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'id_ingredient' => 2,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'id_ingredient' => 3,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 24,
                'id_ingredient' => 12,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'id_ingredient' => 2,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'id_ingredient' => 3,
                'amount' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 25,
                'id_ingredient' => 9,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'id_ingredient' => 1,
                'amount' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'id_ingredient' => 2,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'id_ingredient' => 3,
                'amount' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 26,
                'id_ingredient' => 9,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'id_ingredient' => 2,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'id_ingredient' => 3,
                'amount' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 27,
                'id_ingredient' => 4,
                'amount' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'id_ingredient' => 1,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'id_ingredient' => 2,
                'amount' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'id_ingredient' => 3,
                'amount' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 28,
                'id_ingredient' => 4,
                'amount' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'id_ingredient' => 15,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 29,
                'id_ingredient' => 18,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'id_ingredient' => 1,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'id_ingredient' => 9,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 30,
                'id_ingredient' => 15,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'id_ingredient' => 15,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 31,
                'id_ingredient' => 16,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 32,
                'id_ingredient' => 15,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 32,
                'id_ingredient' => 17,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'id_ingredient' => 15,
                'amount' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'id_ingredient' => 18,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 33,
                'id_ingredient' => 9,
                'amount' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'id_ingredient' => 2,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'id_ingredient' => 9,
                'amount' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 34,
                'id_ingredient' => 12,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 35,
                'id_ingredient' => 2,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 35,
                'id_ingredient' => 18,
                'amount' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 35,
                'id_ingredient' => 12,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'id_ingredient' => 2,
                'amount' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'id_ingredient' => 5,
                'amount' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 36,
                'id_ingredient' => 12,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'id_ingredient' => 1,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'id_ingredient' => 2,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 37,
                'id_ingredient' => 12,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'id_ingredient' => 13,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'id_ingredient' => 2,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 38,
                'id_ingredient' => 12,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'id_ingredient' => 3,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 39,
                'id_ingredient' => 4,
                'amount' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'id_ingredient' => 3,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 40,
                'id_ingredient' => 4,
                'amount' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'id_ingredient' => 2,
                'amount' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 41,
                'id_ingredient' => 6,
                'amount' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'id_ingredient' => 2,
                'amount' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'id_ingredient' => 7,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'id_ingredient' => 1,
                'amount' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'id_ingredient' => 2,
                'amount' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_product' => 42,
                'id_ingredient' => 7,
                'amount' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
